(function () {
  var masters = {
    shippers: [{id:'S1',code:'SHP0001',name:'AE TRADING COMPANY',isActive:true}],
    consignees: [{id:'C1',code:'CNE0001',name:'MAESOT FREEZONE CO.,LTD.',isActive:true}],
    notify: [{id:'N1',code:'NTP0001',name:'KOLA SHIPPING CO.,LTD.',isActive:true}],
    people: [{id:'P1',code:'PIC0001',name:'FAISAL',isActive:true}],
    loadingTypes: [{id:'L1',code:'40HC',name:'40 FT High Cube Container',isActive:true}],
    ports: [{id:'PO1',code:'THLCH',name:'ท่าเรือแหลมฉบัง (Laem Chabang Port)',isActive:true}],
    terminals: [{id:'T1',code:'A2',name:'A2',isActive:true}],
    jobTypes: [{id:'JT1',code:'MU',name:'MSFZ - USED CAR',isActive:true}]
  };
  var invoice = {id:'F2',category:'INVOICE_GOODS',version:2,fileName:'invoice_goods_v2.pdf',isCurrent:true,isAcknowledged:false,changeReason:'แก้ไขยอดเงินสินค้า',uploadedAt:'2026-08-11T03:10:00Z'};
  var jobs = [
    {id:'J1',jobNo:'KOLA-2026-0001',blNo:'OOLU2315365610',sourceType:'AN',shipperId:'S1',consigneeId:'C1',notifyPartyId:'N1',personId:'P1',loadingTypeId:'L1',portId:'PO1',terminalId:'T1',jobTypeId:'JT1',product:'USED VEHICLE',vessel:'GSL MAREN',voyage:'023S',eta:'2026-08-18',status:'WAITING_INVOICE_DO',surrenderStatus:'PENDING',customsStatus:'NOT_STARTED',releaseStatus:'PENDING',demDays:5,detDays:3,unitAmount:17,grossWeight:24610,shipline:'OOCL',hasInvoiceAlert:true,draftStatus:'NOT_STARTED',approvals:{AN:{id:'A1',approvalType:'AN',status:'APPROVED'},FN:null},currentFiles:{ARRIVAL_NOTICE:{id:'F1',category:'ARRIVAL_NOTICE',version:1,fileName:'Arrival Notice.pdf',isCurrent:true},INVOICE_GOODS:invoice}},
    {id:'J2',jobNo:'KOLA-2026-0002',blNo:'MAEU123456789',sourceType:'BL',shipperId:'S1',consigneeId:'C1',notifyPartyId:'N1',personId:'P1',loadingTypeId:'L1',portId:'PO1',terminalId:'T1',jobTypeId:'JT1',product:'USED CAR',vessel:'MAERSK SINGAPORE',voyage:'214W',eta:'2026-08-20',status:'WAITING_AN_APPROVAL',surrenderStatus:'PENDING',customsStatus:'NOT_STARTED',releaseStatus:'PENDING',demDays:7,detDays:14,unitAmount:8,grossWeight:18500,shipline:'MAERSK',hasInvoiceAlert:false,draftStatus:'NOT_STARTED',approvals:{AN:{id:'A2',approvalType:'AN',status:'PENDING'},FN:null},currentFiles:{BL:{id:'F3',category:'BL',version:1,fileName:'Bill of Lading.pdf',isCurrent:true}}},
    {id:'J3',jobNo:'KOLA-2026-0003',blNo:'ONEYBKK001234',sourceType:'AN',shipperId:'S1',consigneeId:'C1',notifyPartyId:'N1',personId:'P1',loadingTypeId:'L1',portId:'PO1',terminalId:'T1',jobTypeId:'JT1',product:'OTHER VEHICLE',vessel:'ONE HARMONY',voyage:'088S',eta:'2026-08-23',status:'FN_APPROVED',surrenderStatus:'CLEARED',customsStatus:'DRAFT',releaseStatus:'PENDING',demDays:5,detDays:5,unitAmount:12,grossWeight:22000,shipline:'ONE',hasInvoiceAlert:false,draftStatus:'CREATED',draftRefNo:'QELS100088489',approvals:{AN:{id:'A3',approvalType:'AN',status:'APPROVED'},FN:{id:'A4',approvalType:'FN',status:'APPROVED'}},currentFiles:{ARRIVAL_NOTICE:{id:'F4',category:'ARRIVAL_NOTICE',version:1,fileName:'AN_ONE.pdf',isCurrent:true},FINAL_INVOICE:{id:'F5',category:'FINAL_INVOICE',version:1,fileName:'Final Invoice.pdf',isCurrent:true}}}
  ];
  function bootstrap(){return {app:{name:'KOLA Import ERP',version:'1.1.0'},user:{id:'U1',username:'admin',displayName:'System Administrator',role:'ADMIN',mustChangePassword:false},jobs:jobs,masters:masters,users:[],dashboard:{total:3,invoiceAlerts:1,waitingAN:1,waitingFN:0,customsDraft:1,released:0}};}
  function detail(id){var job=jobs.find(function(j){return j.id===id;});return {job:job,bls:[{id:'BL1',jobId:id,blNo:job.blNo,shipperId:'S1',shipperName:'AE TRADING COMPANY'}],containers:[{id:'CT1',jobId:id,containerNo:'TLLU6866880',containerType:'40HC',sealNo:'SEAL-001',jobNo:job.jobNo},{id:'CT2',jobId:id,containerNo:'TEMU6284893',containerType:'40HC',sealNo:'SEAL-002',jobNo:job.jobNo}],files:Object.keys(job.currentFiles).map(function(k){return job.currentFiles[k];}),approvals:Object.keys(job.approvals).map(function(k){return job.approvals[k];}).filter(Boolean),customsEntry:job.customsStatus==='DRAFT'?{entryNo:job.draftRefNo,status:'DRAFT'}:null,history:[{toStatus:job.status,note:'สถานะปัจจุบัน',createdAt:'2026-08-11T04:00:00Z'},{toStatus:'WAITING_ENTER_BL',note:'อ่านข้อมูลจาก AN และส่งเข้า Draft',createdAt:'2026-08-10T04:00:00Z'}]};}
  var handlers={authLogin:function(){return {token:'preview-token',user:bootstrap().user};},getBootstrapData:bootstrap,authLogout:function(){return {ok:true};},getJobDetail:function(_token,id){return detail(id);},authChangePassword:function(){return {ok:true};}};
  function runner(success,failure){return new Proxy({}, {get:function(_target,prop){if(prop==='withSuccessHandler')return function(fn){return runner(fn,failure);};if(prop==='withFailureHandler')return function(fn){return runner(success,fn);};return function(){var args=Array.prototype.slice.call(arguments);setTimeout(function(){try{var value=handlers[prop]?handlers[prop].apply(null,args):{ok:true};if(success)success(value);}catch(error){if(failure)failure(error);}},10);};}});}
  window.google={script:{}};
  Object.defineProperty(window.google.script,'run',{get:function(){return runner();}});
}());
